# Generated by Django 3.1.4 on 2021-02-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='numero_Productos',
            field=models.IntegerField(),
        ),
    ]
